insert into CCA.T_CFGCONTAGRAFICA (CODIF, CODREDE, CODSUBREDE, DESCCODIGO, CODIFABASTDEST, CODIFAGRUPDEST)
values ('7033', 25, 1, 'DEPOSITO', '7033', '8033');

insert into CCA.T_CFGCONTAGRAFICA (CODIF, CODREDE, CODSUBREDE, DESCCODIGO, CODIFABASTDEST, CODIFAGRUPDEST)
values ('7033', 25, 2, 'SAQUE', '1033', '1033');

insert into CCA.T_CFGCONTAGRAFICA (CODIF, CODREDE, CODSUBREDE, DESCCODIGO, CODIFABASTDEST, CODIFAGRUPDEST)
values ('7033', 25, 2, 'DEPOSITO', '1033', '2033');

commit;
/
